### ISSUE TITLE
Cant get the 'back' sprite using back = True attribute

### ISSUE THREAD

**Issue by siddhantchimankar** [PokeAPI/pokebase#20]

**Comment by Naramsim** [comment]
What are you meaning by `back=True` attribute?

Are you making an API call?

**Comment by thicco-catto** [comment]
It doesn't seem to work for me either, neither the back sprite or any other keyword like "female" or "official-artwork"

```
import pokebase as pb

s3 = pb.SpriteResource('pokemon', 1, back=True)
```

What i get from this:

`TypeError: __init__() got an unexpected keyword argument 'back'`

**Comment by Naramsim** [comment]
Hm, thanks for reporting. Pinging @GregHilmes

**Comment by GregHilmes** [comment]
Apparently I never did a release with the sprite improvements :thinking: (sorry about that - I'm astounded this has gone unnoticed since 2017). I'll take a look at the discrepancies between the current state of the repo and the PyPI release. The good news is that `master` has this bug fixed. If you need a quick fix, you can try to uninstall pokebase and reinstall with something like `pip install git+https://github.com/PokeAPI/pokebase.git` for the time being, although in all honesty its been so long since I touched this code I'm not sure if that will be stable.

The long-term fix will be to actually create a release with the current state of `master`, though I will take some time to make sure it is stable before doing so. (I'll close this once that release happens)

**Comment by Naramsim** [comment]
Thanks Greg! You could also set up a trigger in Travis that pushes onto Pypi when the `master` is pushed.

Anyway, you are the admin of the Pypi project :)
